# Generated by Django 2.0.2 on 2018-02-23 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('keyserv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Post date'),
            preserve_default=False,
        ),
    ]
